#!/usr/bin/env bash

icon_theme_path="/home/$USER/.local/share/icons/Gruvbox-Material-Dark"

desc="$1"
desc=${desc:-"x"}

icon="$icon_theme_path/16x16/apps/system-restart.svg"

dunstify \
	-i "$icon" \
	"Redémarré:" \
	"$desc"